### ISSUE TITLE
Relacionar OrdenCompra y DetalleCarrito

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p3_g6_sf#18]
**Título:** Implementar relación One-to-Many entre OrdenCompra y DetalleCarrito

**Descripción:**

* Establecer una relación One-to-Many entre las entidades `OrdenCompra` y `DetalleCarrito`.
* Eliminar constructores innecesarios.
* Eliminar las anotaciones `@Table` y `@Column` innecesarias o redundantes.
* En el pull request, adjuntar una imagen del resultado del diagrama de base de datos.

**Archivos involucrados:**

* `OrdenCompra.java`
* `DetalleCarrito.java`

**Comment by ivanSegal** [comment]
![image](https://github.com/ahumadamob/2024_gc_p3_g6_sf/assets/92531339/5c17d31d-a9d6-45e8-a6fd-bbc31aa899af)
