### ISSUE TITLE
Relacionar Producto y OrdenCompra

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p3_g6_sf#20]
**Título:** Implementar relación Many-to-Many entre Producto y OrdenCompra

**Descripción:**

* Establecer una relación Many-to-Many entre las entidades `Producto` y `OrdenCompra` utilizando una tabla intermedia.
* Eliminar constructores innecesarios.
* Eliminar las anotaciones `@Table` y `@Column` innecesarias o redundantes.
* En el pull request, adjuntar una imagen del resultado del diagrama de base de datos.

**Archivos involucrados:**

* `Producto.java`
* `OrdenCompra.java`

**Comment by damimauri92** [comment]
![DER](https://github.com/ahumadamob/2024_gc_p3_g6_sf/assets/132856679/34d5464d-e98b-4024-a8f8-15c636aba249)
