### ISSUE TITLE
Crear persistencia para la entidad Cliente

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p3_g6_sf#30]
Entidad: Cliente

**Título:** Crear persistencia para la entidad Cliente

**Descripción:**

1. Crear los archivos:
  * `ClienteRepository`
  * `IClienteService`
  * `ClienteServiceImpl`
  * `ClienteController`
2. En los servicios, desarrollar los siguientes métodos:
  * `getAll()`
  * `getById(Long id)`
  * `save(Cliente cliente)`
  * `delete(Long id)`
  * `exists(Long id)`

**Ejemplo de la interfaz del servicio:**

    public interface IClienteService {
        List<Cliente> getAll();
        Cliente getById(Long id);
        Cliente save(Cliente cliente);
        void delete(Long id);
        boolean exists(Long id);
    }

**Endpoints en el controlador:**

* `GET /clientes`
* `GET /clientes/{id}`
* `POST /clientes`
* `PUT /clientes/{id}`
* `DELETE /clientes/{id}`

**Instrucciones adicionales:**

* Adjuntar capturas de todas las llamadas a los métodos a través de Postman en el pull request.

**Comment by ahumadamob** [comment]
Has incluido archivos incorrectos en el pull request. Por ejemplo hay archivos .class. 
Comentame si preferis revertirlo con git, o rehacer el trabajo en una nueva rama

**Comment by Alvaro-Antonii** [comment]
Buenas noches profesor, si puede ser en otra rama estarìa bien
