### ISSUE TITLE
Crear persistencia para la entidad OrdenCompra

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p3_g6_sf#32]
Entidad: OrdenCompra

**Título:** Crear persistencia para la entidad OrdenCompra

**Descripción:**

1. Crear los archivos:
  * `OrdenCompraRepository`
  * `IOrdenCompraService`
  * `OrdenCompraServiceImpl`
  * `OrdenCompraController`
2. En los servicios, desarrollar los siguientes métodos:
  * `getAll()`
  * `getById(Long id)`
  * `save(OrdenCompra ordenCompra)`
  * `delete(Long id)`
  * `exists(Long id)`

**Ejemplo de la interfaz del servicio:**

    public interface IOrdenCompraService {
        List<OrdenCompra> getAll();
        OrdenCompra getById(Long id);
        OrdenCompra save(OrdenCompra ordenCompra);
        void delete(Long id);
        boolean exists(Long id);
    }

**Endpoints en el controlador:**

* `GET /ordenesCompra`
* `GET /ordenesCompra/{id}`
* `POST /ordenesCompra`
* `PUT /ordenesCompra/{id}`
* `DELETE /ordenesCompra/{id}`

**Instrucciones adicionales:**

* Adjuntar capturas de todas las llamadas a los métodos a través de Postman en el pull request.

**Comment by ahumadamob** [comment]
Adjuntar capturas de todas las llamadas a los métodos a través de Postman en el pull request.

**Comment by Alvaro-Antonii** [comment]
![or3](https://github.com/ahumadamob/2024_gc_p3_g6_sf/assets/121462858/7a66511a-8068-4007-a2cf-adc016eeb5b4)
![orde1](https://github.com/ahumadamob/2024_gc_p3_g6_sf/assets/121462858/a3edfcda-55be-416d-a50b-19741d0b6d62)
![or2](https://github.com/ahumadamob/2024_gc_p3_g6_sf/assets/121462858/0ea94663-34dc-428d-8243-fc7040dfd34b)
![OR4](https://github.com/ahumadamob/2024_gc_p3_g6_sf/assets/121462858/a2f1bfe5-08ff-4900-9c90-f8e9b509a931)
![OR5](https://github.com/ahumadamob/2024_gc_p3_g6_sf/assets/121462858/ef1e2d4f-9cc8-4244-8ab7-6fcbfd221f41)
Adjunto las imàgenes de postman
