### ISSUE TITLE
Persistencia completa de la entidad Producto

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p3_g6_sf#44]

**Comment by ivanSegal** [comment]
![image](https://github.com/user-attachments/assets/46f641f2-19c2-4425-b478-0e6d76d13543)
![image](https://github.com/user-attachments/assets/e6e52738-eb5c-4ee5-88fb-67137581c582)
![image](https://github.com/user-attachments/assets/61d0e98c-47bd-4f2a-b179-9a4a531923f2)
![image](https://github.com/user-attachments/assets/8c8a9a66-9700-4e74-b91b-1b1868ac1614)

**Comment by ahumadamob** [comment]
La tarea tiene comentarios para resolver

**Comment by ivanSegal** [comment]
Agregué las validaciones a la clase Producto en un nuevo commit
